#!/bin/bash
# Schedule Feb 9-15 Threads content to Postiz

API_KEY="75453381e58be37ec19683c7c921e91bd7d3cc0adfbcc609e881c861e20e5437"
THREADS_ID="cmlbamgkt008som0y7z6sl86w"

BASE_URL="https://api.postiz.com/public/v1"

schedule_post() {
    local date_str=$1
    local content=$2
    
    curl -s -X POST "$BASE_URL/posts" \
        -H "Authorization: $API_KEY" \
        -H "Content-Type: application/json" \
        -d "{
            \"type\": \"schedule\",
            \"date\": \"$date_str\",
            \"shortLink\": false,
            \"tags\": [\"feb9-15\", \"auto-scheduled\"],
            \"posts\": [{
                \"integration\": {\"id\": \"$THREADS_ID\"},
                \"value\": [{\"content\": \"$content\"}]
            }]
        }" | jq -r '.id // .msg'
}

echo "=== Scheduling Threads Posts ==="

# MONDAY FEB 9
schedule_post "2026-02-09T08:30:00.000Z" "The sportswear M&A wave isn't coming. It's already here.\\n\\nAdidas dropped Yeezy. Nike's innovation pipeline dried up. VF Corp unloaded Supreme. The giants are bleeding, and private equity smells blood.\\n\\nBut here's what most analysts miss: the real targets aren't the struggling giants. They're the tier-two players with authentic heritage and efficient operations.\\n\\nOn Running, Hoka, Salomon—these brands built loyal communities without celebrity dependency. That's worth more than any logo.\\n\\nWhen the acquisition announcements drop, don't be surprised."

schedule_post "2026-02-09T12:30:00.000Z" "Why Supreme sold for less than its 2020 valuation:\\n\\n→ Skate culture went mainstream (bad for exclusivity)\\n→ Resale market ate primary margins\\n→ Gen Z doesn't queue for drops, they scroll\\n\\nVF Corp learned the hard way: hype isn't a business model. Authenticity without operational excellence is just nostalgia.\\n\\nThe next wave of M&A will prioritize unit economics over brand heat. Buyers want profitable communities, not viral moments.\\n\\nSmart money is betting on retention, not acquisition."

schedule_post "2026-02-09T18:30:00.000Z" "Three sportswear acquisition predictions for 2025:\\n\\n1. A resale platform gets bought by a major brand (not just partnerships—full acquisition)\\n\\n2. A running brand gets PE backing and goes on a buying spree of smaller niche labels\\n\\n3. A legacy brand sells its licensing business to focus on core product\\n\\nThe consolidation phase always favors operators over marketers. Watch who has the margins, not just the mentions."

# TUESDAY FEB 10
schedule_post "2026-02-10T08:30:00.000Z" "Every retailer is \"exploring AI\" right now.\\n\\nBut there's a massive difference between conversational AI (chatbots customers hate) and operational AI (systems that quietly save millions).\\n\\nThe real ROI isn't in replacing customer service. It's in:\\n\\n→ Predictive inventory that cuts carrying costs by 30%+\\n→ Dynamic pricing that responds to demand signals in hours, not weeks\\n→ Assortment optimization that knows what each store needs before the season starts\\n\\nZara's parent company Inditex invested over €1B in AI-driven logistics. Their 2-week design-to-shelf cycle isn't magic—it's math. Competitors are stuck at 6 months.\\n\\nThe gap between AI-native operations and legacy retail is widening fast."

schedule_post "2026-02-10T12:30:00.000Z" "Why fashion returns cost brands 15-25% of revenue:\\n\\nWrong size. Wrong fit expectations. Wrong color representation.\\n\\nAI is solving this three ways:\\n\\n1. Virtual try-on reducing fit uncertainty\\n2. Predictive sizing based on purchase + return patterns\\n3. Better product imagery that matches real-world appearance\\n\\nEvery return prevented is pure margin recovered. At scale, this is worth billions.\\n\\nThe brands investing here now will have structurally better economics in 2026. The ones still debating AI strategy will be explaining margin compression to investors."

schedule_post "2026-02-10T18:30:00.000Z" "Three AI applications actually moving the needle in fashion retail:\\n\\n1. Demand sensing that adjusts production 6+ weeks before traditional forecasting catches up. Zara-level responsiveness for everyone else.\\n\\n2. Visual search that converts browsers to buyers. Pinterest and Google Lens trained customers. Smart retailers are capturing that intent.\\n\\n3. Automated trend detection scanning social signals, search patterns, and early sales velocity. Not predicting the future—seeing the present faster than competitors.\\n\\nThese aren't experiments. They're operational advantages compounding daily."

# WEDNESDAY FEB 11
schedule_post "2026-02-11T08:30:00.000Z" "Resale was the disruptor. Now it's being disrupted.\\n\\nThe 2010s narrative was simple: circular is the future, Gen Z loves sustainability, resale platforms will eat fast fashion's lunch.\\n\\nAll true. But incomplete.\\n\\nWhat nobody modeled: authentication costs don't scale linearly. Every luxury item needs expert verification. At volume, that's a massive cost center. The RealReal's margin pressure isn't a demand problem—it's an operations problem.\\n\\nAdd oversupply of hype products (Yeezy flooding the market), platform fatigue (how many apps can consumers maintain?), and luxury brands launching their own resale channels.\\n\\nThe standalone resale platforms that survive will have either proprietary authentication tech or exclusive brand partnerships. Everyone else is commodity."

schedule_post "2026-02-11T12:30:00.000Z" "Why luxury brands are building resale instead of fighting it:\\n\\n→ Capture margin from the second transaction\\n→ Control authentication standards\\n→ Access customer data from secondary buyers\\n→ Protect brand perception (no fakes in \"official\" resale)\\n\\nGucci Vault, Richemont's Watchfinder, Prada's pre-owned program—these aren't sustainability gestures. They're vertical integration.\\n\\nThe playbook: sell once at full price, capture resale commission, maintain brand control.\\n\\nStandalone platforms are now competing with the brands whose products they sell. That's a structural disadvantage."

schedule_post "2026-02-11T18:30:00.000Z" "Three predictions for resale in 2025:\\n\\n1. At least one major resale platform gets acquired by a luxury conglomerate—not for the brand, but for the authentication infrastructure.\\n\\n2. Authentication tech becomes the differentiator. Computer vision + spectroscopy at scale. Platforms without it become marketplaces with quality problems.\\n\\n3. Brand-owned resale captures 30%+ of secondary market volume in luxury categories. Standalone platforms pivot to mid-market or niche verticals.\\n\\nThe circular economy thesis remains correct. But the business model is consolidating."

# THURSDAY FEB 12
schedule_post "2026-02-12T08:30:00.000Z" "The China luxury story everyone's telling: consumption collapsed, youth are broke, luxury is doomed.\\n\\nThe real story: consumption fragmented across channels and geographies, and most brands are still optimizing for the old pattern.\\n\\nHere's what's actually happening:\\n\\nDomestic luxury spending in China is softer than 2019, but not catastrophic. The duty-free Hainan island strategy is working—luxury malls are packed. And Chinese travelers are back, but they're shopping in Japan (weak yen = 20-30% discount on European brands) instead of Europe.\\n\\nThe customer didn't disappear. The location did.\\n\\nBrands optimizing for 2019's \"wealthy Chinese tourist in Paris\" model are seeing numbers drop. Brands with strong Hainan presence and Japan inventory are quietly winning."

schedule_post "2026-02-12T12:30:00.000Z" "Why Japan is becoming China's luxury shopping mall:\\n\\n→ Yen at multi-decade lows = 20-30% effective discount\\n→ Geographic proximity = short trips possible\\n→ Weaker import restrictions than Europe\\n→ Xiaohongshu culture amplifies the \"smart shopping\" narrative\\n\\nChinese travelers in Japan spend more per capita on luxury than Japanese locals. And they post about it, creating a feedback loop.\\n\\nThe luxury brands seeing soft China numbers in Q3? Many of them had inventory and marketing optimized for Shanghai and Paris. Not Tokyo.\\n\\nGeographic strategy matters more than ever."

schedule_post "2026-02-12T18:30:00.000Z" "Three implications of China's fragmented luxury market:\\n\\n1. Same-store sales in Chinese malls will underperform for years. The traffic is never coming back to that format. Hainan and cross-border are the new normal.\\n\\n2. Japan needs to be treated as a China-adjacent market, not a domestic one. Chinese language service, payment integration, and inventory planning should reflect this.\\n\\n3. The brands winning are those with flexible geographic strategy. LVMH and Hermès can shift inventory and marketing spend across regions. Smaller brands stuck in long-term boutique leases are trapped in the wrong locations.\\n\\nThe China customer is still spending. The question is whether you're where they're shopping."

# FRIDAY FEB 13
schedule_post "2026-02-13T08:30:00.000Z" "The sneaker resale market contracted 25%+ from its 2021 peak. Most analysts blame the economy. They're half right.\\n\\nThe real driver: brands killed their own golden goose.\\n\\nWhen resale margins hit 300-500% on limited drops, brands saw lost revenue, not market validation. Their response? Increase supply, add restocks, widen distribution.\\n\\nScarcity requires restraint. Public companies don't do restraint well.\\n\\nThe result: resale prices collapsed, but so did the cultural capital. When everyone can get the shoe, nobody wants it. Nike's DTC push trained customers to expect access, not earn it.\\n\\nThe brands winning now—New Balance, Asics, niche running labels—understand that cultural cache compounds slowly and evaporates quickly."

schedule_post "2026-02-13T12:30:00.000Z" "Why Nike's SNKRS app became a case study in algorithmic fatigue:\\n\\nThe promise: exclusive access for true fans.\\n\\nThe reality: bots, crashes, and a lottery system that trained customers to expect disappointment.\\n\\nWhen scarcity becomes randomness, the game stops being fun. The psychological reward of \"winning\" a drop requires the possibility of losing. But SNKRS made losing so common that participation dropped.\\n\\nMeanwhile, New Balance releases a few excellent collaborations annually. No app required. No lottery. Just consistent quality and organic demand.\\n\\nThe lesson: algorithms can distribute product, but they can't manufacture desire. That still requires human judgment and restraint."

schedule_post "2026-02-13T18:30:00.000Z" "Three shifts in sneaker economics for 2025:\\n\\n1. The collaboration bubble is popping. 47 Travis Scott drops later, the market is exhausted. Future wins will be rare, not frequent.\\n\\n2. Running technology (carbon plates, foam compounds) is the new design language. Performance credibility beats celebrity association.\\n\\n3. Regional exclusives replace global hype. Limited Japan-only or EU-only drops create real scarcity without flooding any single market.\\n\\nThe brands that win will act like private companies with public balance sheets. Long-term cultural investment over quarterly revenue optimization."

# SATURDAY FEB 14
schedule_post "2026-02-14T08:30:00.000Z" "Every February, the \"is fashion week still relevant?\" debate resurfaces.\\n\\nWrong question.\\n\\nFashion week isn't dying—it's unbundling into separate functions that no longer require the same container.\\n\\nThe runway show became content creation for social distribution. The see-now-buy-now model collapsed (production realities), but immediate digital drops replaced it. The audience shifted from department store buyers to TikTok creators and investment analysts.\\n\\nCopenhagen Fashion Week added sustainability certification requirements. Paris didn't. London and Milan are somewhere in between.\\n\\nThe result: geographic fashion weeks are becoming policy differentiators. Copenhagen for sustainability credibility. Paris for heritage and scale. New York for commercial accessibility.\\n\\nRelevance isn't binary anymore. It's segmented."

schedule_post "2026-02-14T12:30:00.000Z" "Why fashion week front rows look like creator conferences now:\\n\\nThe math changed. A buyer from a major department store might place a $500K order. A TikTok creator with 10M followers generates $2M+ in attributed sales through affiliate links and \"get ready with me\" content.\\n\\nThe brands know this. Front row seats are allocated based on content ROI, not historic relationships.\\n\\nBut there's a catch: authenticity. When every show is optimized for social performance, the signal-to-noise ratio drops. Audiences can smell manufactured moments.\\n\\nThe brands winning fashion week 2025 will balance creator access with genuine creative vision. Content-factory shows feel empty. Substance with distribution wins."

schedule_post "2026-02-14T18:30:00.000Z" "Three predictions for fashion week evolution:\\n\\n1. Copenhagen's sustainability mandate becomes the template. Other fashion weeks add environmental requirements or lose relevance with younger talent and conscious consumers.\\n\\n2. Physical attendance becomes even more exclusive, while digital access becomes ubiquitous. The show is for 200 people. The content is for 200 million.\\n\\n3. Collections fragment into \"fashion week pieces\" (statement, editorial) and \"commercial pieces\" (selling online immediately). The six-month lag was already broken. Now it's fully separated.\\n\\nThe calendar is legacy infrastructure. The moments are what matter."

# SUNDAY FEB 15
schedule_post "2026-02-15T08:30:00.000Z" "Weekly synthesis: Feb 9-15\\n\\nSix themes, one pattern:\\n\\nSportswear M&A taught us the giants are vulnerable and second-tier brands with authentic communities are the real targets.\\n\\nAI in retail showed that operational applications (inventory, pricing, forecasting) generate ROI while conversational AI remains a cost center.\\n\\nResale evolution revealed that authentication costs don't scale and brand-owned secondary markets are winning.\\n\\nChina luxury demonstrated that the customer didn't disappear—they just shop in Hainan and Tokyo now.\\n\\nSneaker economics proved that scarcity requires restraint, and public companies struggle with restraint.\\n\\nFashion week illustrated how relevance unbundles into content creation, policy differentiation, and investor relations.\\n\\nThe throughline: Implementation speed is the new competitive advantage. Same insights, different execution timelines, compounding returns."

schedule_post "2026-02-15T12:30:00.000Z" "What I got wrong this week (and what I'm watching):\\n\\nThe M&A timeline might be slower than I suggested. Private equity is cautious, and brand valuations haven't fully adjusted. Q2 might be when deals actually happen.\\n\\nAI implementation is faster than expected in mid-market retail. The tools are democratizing quicker than the giants can build proprietary systems. Watch for mid-tier brands leapfrogging.\\n\\nResale authentication tech might solve the unit economics problem faster than predicted. Computer vision + spectroscopy startups are getting surprisingly accurate. TheRealReal's struggles might be company-specific, not model-specific.\\n\\nChina travel patterns to Japan could shift if yen strengthens. Watch currency markets—they're driving luxury geography right now."

schedule_post "2026-02-15T18:30:00.000Z" "Looking ahead: Feb 16-22\\n\\nWhat I'll be tracking:\\n\\n→ Any sportswear M&A announcements (expectations vs. reality)\\n→ Retail earnings calls for AI implementation mentions (frequency = priority)\\n→ Resale platform fundraising or acquisition rumors\\n→ Chinese New Year travel data (luxury spend patterns)\\n→ Nike/Adidas new release calendars (scarcity strategy signals)\\n→ Milan Fashion Week sustainability commitments (Copenhagen effect spreading?)\\n\\nThe framework: Look for speed of implementation, not just strategic intent. Everyone has the same PowerPoints. Few have the operational changes.\\n\\nIf you're building in fashion/luxury/sportswear, the window for being early on these shifts is closing. The window for being competent is opening."

echo ""
echo "=== Threads Posts Scheduled ==="
