#!/bin/bash
# Schedule Feb 9-15 Instagram content to Postiz

API_KEY="75453381e58be37ec19683c7c921e91bd7d3cc0adfbcc609e881c861e20e5437"
IG_ID="cmlbfgpqi00jdom0y14555fls"

BASE_URL="https://api.postiz.com/public/v1"

schedule_post() {
    local date_str=$1
    local content=$2
    
    curl -s -X POST "$BASE_URL/posts" \
        -H "Authorization: $API_KEY" \
        -H "Content-Type: application/json" \
        -d "{
            \"type\": \"schedule\",
            \"date\": \"$date_str\",
            \"shortLink\": false,
            \"tags\": [\"feb9-15\", \"auto-scheduled\", \"instagram\"],
            \"posts\": [{
                \"integration\": {\"id\": \"$IG_ID\"},
                \"value\": [{\"content\": \"$content\"}]
            }]
        }" | jq -r '.id // .msg'
}

echo "=== Scheduling Instagram Posts ==="

# MONDAY FEB 9 - Sportswear M&A
schedule_post "2026-02-09T16:00:00.000Z" "The sportswear industry is entering its consolidation era—and most people are watching the wrong deals.\\n\\nEveryone's focused on Kanye's exit, Nike's stumbles, or Supreme's fire sale. But the real story is happening one tier down.\\n\\nOn Running. Hoka. Salomon. These brands built something the giants lost: authentic community without celebrity dependency. When you're not renting influence, you own your margin.\\n\\nVF Corp selling Supreme taught the market a brutal lesson: hype without operational excellence is just expensive nostalgia. The next acquisitions won't chase viral moments—they'll chase retention rates.\\n\\nPrivate equity is already circling. The targets? Brands with efficient DTC operations, real resale integration, and communities that buy consistently—not just during drops.\\n\\nThe playbook is shifting from \"acquire cool\" to \"acquire capability.\" Watch for deals involving AI sizing tech, resale logistics, and sustainable manufacturing infrastructure.\\n\\nThe brands that survive won't be the loudest. They'll be the ones with the best unit economics."

# TUESDAY FEB 10 - AI in Retail
schedule_post "2026-02-10T16:00:00.000Z" "The AI conversation in fashion retail is happening at the wrong level.\\n\\nEveryone's fixated on chatbots and virtual stylists—shiny objects that barely move the needle. The real transformation is invisible, operational, and already separating winners from losers.\\n\\nZara's parent company Inditex didn't build a chatbot. They built a €1B+ logistics engine that compresses design-to-shelf from 6 months to 2 weeks. That's not automation—that's a structural moat.\\n\\nHere's where AI is actually generating ROI:\\n\\nPredictive inventory systems that cut carrying costs by 30%+. Dynamic pricing that responds to demand in hours, not weeks. Visual search capturing purchase intent from Pinterest and Google Lens. Automated trend detection seeing signals 6 weeks before traditional forecasting.\\n\\nThe gap between AI-native operations and legacy retail is widening. Not because of technology availability—because of implementation speed.\\n\\nThe retailers winning in 2025 aren't debating AI strategy. They're already capturing the margin from fewer returns, faster turns, and optimal assortment mix.\\n\\nSpeed is the new moat. AI is just the engine."

# WEDNESDAY FEB 11 - Resale Evolution
schedule_post "2026-02-11T16:00:00.000Z" "Resale has reached its awkward adolescent phase—and the growing pains are showing.\\n\\nThe narrative of the 2010s was irresistible: sustainability meets profit, Gen Z ditches fast fashion, resale platforms become the new retail giants. The growth was real—25X faster than fast fashion in the last decade.\\n\\nBut the unit economics are catching up.\\n\\nAuthentication at scale is expensive. Every luxury handbag needs expert verification, and AI hasn't solved this yet. The RealReal's struggles aren't about demand—they're about the cost of being certain.\\n\\nMeanwhile, luxury brands stopped fighting resale and started building it. Gucci Vault. Richemont's Watchfinder. Prada's pre-owned program. These aren't sustainability gestures—they're vertical integration plays. Sell once at full price, capture resale commission, control authentication standards, own the customer relationship twice.\\n\\nStandalone platforms now face a structural disadvantage: they're competing with the very brands whose products they sell.\\n\\nThe winners will be platforms with proprietary authentication technology or exclusive brand partnerships. Everyone else becomes a commodity marketplace.\\n\\nThe circular economy thesis is intact. But the business model is consolidating fast."

# THURSDAY FEB 12 - China Luxury
schedule_post "2026-02-12T16:00:00.000Z" "The China luxury market isn't collapsing—it's fragmenting across geographies, and most brands are optimizing for a customer who no longer shops where they're looking.\\n\\nThe headlines focus on soft domestic spending. But dig into LVMH's Q3 numbers: Chinese customer spend on LVMH brands globally was essentially flat. The same customers. The same budgets. Just different locations.\\n\\nHere's the new map:\\n\\nHainan island—China's duty-free paradise—is booming. Luxury malls are packed with domestic tourists buying European brands at tax-free prices. Meanwhile, Chinese international travelers are back, but they've rerouted. Japan's multi-decade weak yen makes it a 20-30% discount shopping destination for European luxury. Tokyo boutiques are seeing Chinese spending at Paris 2019 levels.\\n\\nThe geographic arbitrage is real. A €3,000 handbag in Paris costs effectively €2,200 in Tokyo for Chinese buyers accounting for exchange rates. And Xiaohongshu amplifies the narrative—shopping in Japan isn't just cheaper, it's \"smart.\"\\n\\nBrands with rigid geographic strategies—locked into long-term leases in Shanghai and Paris malls—are reporting declining numbers. Brands with flexible inventory and marketing allocation are capturing the same customers in new locations.\\n\\nThe China luxury consumer didn't disappear. The question is whether your boutique is where they're actually shopping."

# FRIDAY FEB 13 - Sneaker Economics
schedule_post "2026-02-13T16:00:00.000Z" "The sneaker market is experiencing a forced correction—and it's revealing which brands understand cultural economics versus which ones just chased quarterly numbers.\\n\\nThe resale market contracted 25%+ from its 2021 peak. Most coverage blames economic uncertainty. The real story is more interesting: brands killed their own scarcity advantage.\\n\\nWhen resale margins hit 300-500%, public companies saw lost revenue instead of market validation. Their solution? Increase supply, add restocks, widen distribution. Nike's DTC push was supposed to capture resale margin. Instead it trained customers to wait for discounts and expect exclusive access as a baseline.\\n\\nThe problem: scarcity requires restraint. Algorithms don't have restraint.\\n\\nMeanwhile, the brands quietly winning—New Balance, Asics, niche running labels—are running the opposite playbook. Fewer releases. Better product. No oversaturation. Letting demand compound organically rather than manufacturing it monthly.\\n\\nThe cultural capital of sneakers was built on exclusivity, storytelling, and patience. Those don't compress into quarterly earnings cycles.\\n\\nThe new winners will act like private companies with public balance sheets. Long-term cultural investment over short-term revenue extraction. The lesson from 2021's peak: hype has a ceiling. Culture doesn't."

# SATURDAY FEB 14 - Fashion Week
schedule_post "2026-02-14T16:00:00.000Z" "Fashion Week isn't dying—it's being unbundled into distinct functions that no longer require the same container.\\n\\nThe February cycle always brings the \"is fashion week still relevant?\" debate. But look closer: relevance hasn't disappeared, it's fragmented across different formats and audiences.\\n\\nThe runway show is now content creation first, garment presentation second. The front row shifted from department store buyers to TikTok creators with 10M+ followers—influence economics made that inevitable. A single viral \"get ready with me\" video can drive more attributed sales than a traditional wholesale order.\\n\\nGeographic differentiation is emerging. Copenhagen Fashion Week now requires sustainability certifications—positioning itself as the credibility platform for conscious fashion. Paris maintains heritage dominance. New York optimizes for commercial accessibility. The fashion weeks are becoming policy differentiators, not just calendar placeholders.\\n\\nThe most interesting shift: the six-month see-now-buy-now lag is fully broken. Collections now split into \"fashion week pieces\" for editorial and statement, and \"commercial pieces\" selling online immediately. The infrastructure separated from the moment.\\n\\nFashion week 2025 belongs to brands balancing creator access with genuine creative vision. Content-factory shows feel manufactured and audiences can tell. Substance with distribution beats performance without purpose.\\n\\nThe calendar is legacy. The moments are what matter."

# SUNDAY FEB 15 - Weekly Recap
schedule_post "2026-02-15T16:00:00.000Z" "Weekly synthesis: What six major themes revealed about fashion, luxury, and sportswear.\\n\\nThis week's deep dives surfaced a single throughline across every category: the gap between strategic insight and operational implementation is becoming the primary competitive battlefield.\\n\\nSportswear M&A showed us that second-tier brands with authentic communities are more attractive targets than struggling giants—but private equity caution means deals might not close as fast as headlines suggest.\\n\\nAI in retail demonstrated that operational applications (inventory optimization, dynamic pricing, predictive sizing) are generating real ROI while conversational AI remains expensive theater. The surprise: mid-market brands are implementing faster than luxury giants, potentially leapfrogging through democratized tools.\\n\\nResale evolution revealed authentication as the chokepoint that doesn't scale—unless computer vision and spectroscopy breakthroughs accelerate faster than expected. Brand-owned resale channels (Gucci Vault, Richemont's Watchfinder) are vertical integration plays, not sustainability gestures.\\n\\nChina luxury proved the customer didn't disappear, they just fragmented across Hainan duty-free and Tokyo's weak-yen advantage. Geographic flexibility now matters more than flagship locations.\\n\\nSneaker economics confirmed that scarcity requires restraint—a quality public companies struggle to maintain. The brands winning (New Balance, Asics) run patient playbooks while giants chase quarterly numbers.\\n\\nFashion week illustrated relevance unbundling into content creation, policy differentiation, and investor relations. Copenhagen's sustainability mandate is becoming a template. Physical exclusivity and digital ubiquity now coexist.\\n\\nThe pattern: Everyone has the same strategic PowerPoints. Few have the operational changes. The cycle has turned from growth-at-all-costs to margin-preservation-through-execution.\\n\\nBuilding in this space? The early-mover window is closing. The competence window is opening."

echo ""
echo "=== Instagram Posts Scheduled ==="
